{
    "name": "Myanmar NRC",
    "author": "Agga, IdeaCode Academy",
    "depends": ["base", "contacts"],
    "data": [
        "data/1KachinState.xml",
        "data/2KayahState.xml",
        "data/3KayinState.xml",
        "data/4ChinState.xml",
        "data/5SagaingRegion.xml",
        "data/6TanintharyiRegion.xml",
        "data/7BagoRegion.xml",
        "data/8MagwayRegion.xml",
        # "data/9NaypyidawUnionTerritoryRegion.xml",
        "data/9MandalayRegion.xml",
        "data/10MonState.xml",
        "data/11RakhineState.xml",
        "data/12YangonRegion.xml",
        "data/13ShanState.xml",
        "data/14AyeyarwadyRegion.xml",

        "security/ir.model.access.csv",
        "views/res_country_state_township.xml",
        "views/res_partner.xml",
        "views/menus.xml",
    ],
    "images": ["static/description/img.png"],

    "installable": True,
    "license": "LGPL-3",
}
